version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    # ports:
    #   - "2345:2345"
    network_mode: service:localstack
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4510:4510"
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data: